title: Christian Schied
email: christian.schied@outlook.de
description: >-
  © 2026 Christian Schied. Alle Rechte vorbehalten.
baseurl: ""
url: "christian-schied.de"
lang: de

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - werke.md
  - about.md
